name: "Telegram Notification"

on:  
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
  workflow_dispatch:

jobs:
  telegram-notify:
    runs-on: ubuntu-latest
    steps:
      - name: send notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          video: https://Philopho.github.io/alpha-data-2024-06-02/timelapse.mp4
          message: | 
            The ${{ github.event_name }} event triggered final step.
            https://Philopho.github.io/alpha-data-2024-06-02/
